# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    jwt_secret: Epitech42WorkeeJwtSecret
    upload_directory: '%kernel.project_dir%/public'
    mercure_hub_url: 'https://mercure.brangers.eu'
    encrypt_key: "a8MHdKzY7DOi3U+IjrGScwE+Qh7Nv9kYpSxiKJ5NT38="
    rgpd_document: '%kernel.project_dir%/public/LegalDocuments/rgpd.html'
    cgu_document: '%kernel.project_dir%/public/LegalDocuments/CGU.pdf'
    unprotected_routes: [ '/api/login', '/api/register' ]

services:

    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
    _instanceof:
        App\Infrastructure\Doctrine\Type\AbstractEnumType:
            tags: ['app.doctrine_enum_type']


    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'

    App\Infrastructure\FileUploader\Services\FileUploader:
        arguments:
            $targetDirectory: '%upload_directory%'

    App\Core\Components\Notification\UseCase\NotificationHandler:
        arguments:
            $mercureHubUrl: '%mercure_hub_url%'

    App\Core\Components\Notification\UseCase\TestHandler:
        arguments:
            $mercureHubUrl: '%mercure_hub_url%'
            
    App\Client\Controller\LegalDocuments\LegalDocumentsController:
        arguments:
            $rpgdDocumentPath : '%rgpd_document%'
            $cguDocumentPath : '%cgu_document%'

    App\Core\Components\Feedback\UseCase\SelectDailyFeedbackTeamPreferencesHandler:
        arguments:
            $mercureHubUrl: '%mercure_hub_url%'
    
    App\Core\Components\Feedback\UseCase\TeamNeedsToSendFeedbackListener:
        arguments:
            $mercureHubUrl: '%mercure_hub_url%'
    
    App\Infrastructure\Security\CheckSecurityHttpKernelListener:
        arguments:
            $unprotectedRoutes: '%unprotected_routes%'


    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
