doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Company:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Core/Components/Company/Entity'
                prefix: App\Core\Components\Company\Entity
                alias: Company
            User:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Core/Components/User/Entity'
                prefix: App\Core\Components\User\Entity
                alias: User
            Team:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Core/Components/Team/Entity'
                prefix: App\Core\Components\Team\Entity
                alias: Team
            Job:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Core/Components/Job/Entity'
                prefix: App\Core\Components\Job\Entity
                alias: Job
            HumidityMetric:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Core/Components/EnvironmentMetrics/Entity'
                prefix: App\Core\Components\EnvironmentMetrics\Entity
                alias: HumidityMetric
            TemperatureMetric:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Core/Components/EnvironmentMetrics/Entity'
                prefix: App\Core\Components\EnvironmentMetrics\Entity
                alias: TemperatureMetric
            SoundMetric:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Core/Components/EnvironmentMetrics/Entity'
                prefix: App\Core\Components\EnvironmentMetrics\Entity
                alias: SoundMetric
            Notification:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Core/Components/Notification/Entity'
                prefix: App\Core\Components\Notification\Entity
                alias: Notification

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
