name: Check & fix styling

on: [pull_request]

jobs:
    php-cs-fixer:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: install dependencies
              run: cd workee_backend && composer install && cd tools/php-cs-fixer && composer install

            - name: Run PHP CS Fixer
              run: cd workee_backend && tools/php-cs-fixer/vendor/bin/php-cs-fixer fix src --diff --dry-run && tools/php-cs-fixer/vendor/bin/php-cs-fixer fix tests --diff --dry-run
