
on: [pull_request]
name: Main
jobs:
  php-cs-fixer:
    name: PHP-CS-Fixer
    runs-on: ubuntu-latest
    steps:
    - name: change directory
      run: cd workee_backend
    - uses: actions/checkout@v2
    - name: PHP-CS-Fixer
      run: docker run --rm -it -w=/app -v ${PWD}:/app oskarstark/php-cs-fixer-ga:latest
