name: phpstan
on: [pull_request]

jobs:
  build:
    env:
      working-directory: workee_backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest
      - name: PHPStan
        uses: chindit/actions-phpstan@master
        with:
          # Arguments to add to PHPStan
          arguments: 'src/ --level=4'