name: phpstan
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./workee_backend/
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run:  pwd || composer install
      - name: Run phpstan
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6 # or alternative dependency management
      - uses: php-actions/phpstan@v3
        with:
          path: src/
