name: Run Static analysis

on: [pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: php-actions/composer@v6 # or alternative dependency management
    - uses: php-actions/phpstan@v3
      with:
        path: ./workee_backend/src/
        autoload_file: ./workee_backend/vendor/autoload.php