name: phpstan
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      working-directory: ./workee_backend
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run:  pwd || composer install
      - name: Run phpstan
        uses: actions-x/phpstan@v1
        env:
          working-directory: ./workee_backend
        with:
          paths: src/
          level: 0 # min : 0 - max : 8
          phpstanVersion: ^0.12.30
          arguments: --autoload-file vendor/autoload.php
