name: phpstan
on: [pull_request]

env:
  working-directory: workee_backend

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: cd workee_backend || composer install
      - name: PHPStan
        uses: chindit/actions-phpstan@master
        with:
          # Arguments to add to PHPStan
          path: workee_backend/src/

