name: Run Static analysis

on: [pull_request]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: cd workee_backend && composer install
    - name: Run PhpStan
      run: cd workee_backend && vendor/bin/phpstan analyse src --level 3
