name: phpstan
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: cd workee_backend || composer install
      - name: PHPStan
        run: cd workee_backend || vendor/bin/phpstan analyse src --level 4
