name: Create pull request
on: [push]

jobs:
  prForMasterBranch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: update master branch
          title: Update master branch
          branch: temp
