name: Create production promotion pull request
on: [push]

jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - name: Reset promotion branch
        run: |
          git fetch origin master:master
          git reset --hard master
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: temp-promotion
