name: Create production promotion pull request
on: [push]

jobs:
  productionPromotion:
    runs-on: ubuntu-latest
    steps:
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
